version: '3'
services:
  nginx:
      image: nginx
      container_name: nginx
      restart: always
      ports:
          - "80:80"
      volumes:
          - "/opt/docker_data/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro"
