version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
        - wp_vars.myenv
    networks:
        - wordpressnet

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
        - mysql_vars.myenv
    networks:
        - wordpressnet

  adminer:
    image: adminer
    restart: always
    ports:
        - 8081:8080
    networks:
        - wordpressnet

#create network
networks:
  wordpressnet:
    driver: bridge
