version: '3'
services:
  jenkins:
      image: jenkins/jenkins:lts
      container_name: JenkinsMaster
      restart: always
      env_file:
          - vars.env
      ports:
          - "8080:8080"
          - "50000:50000"
      volumes:
          - "/opt/docker_data/jenkins:/var/jenkins_home"
