version: '3'
services:
  jenkins:
      image: jenkins/jenkins:lts
      container_name: JenkinsMaster
      restart: always
      env_file:
          - jenkins.env
      volumes:
          - "/opt/docker_data/jenkins:/var/jenkins_home"
      networks:
          - jenkinsnet

  nginx:
      image: nginx
      container_name: nginx
      restart: always
      ports:
          - "80:80"
      links:
          - jenkins
      volumes:
          - "/opt/docker_data/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      networks:
          - jenkinsnet

#create network
networks:
  jenkinsnet:
    driver: bridge


#
